Update pre-push check

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,24 +1,24 @@
-#!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
+# #!/usr/bin/env sh
+# . "$(dirname -- "$0")/_/husky.sh"
 
-RED='\033[0;31m'
-BLUE='\033[0;34m'
-GRAY='\033[1;30m'
-NC='\033[0m'
+# RED='\033[0;31m'
+# BLUE='\033[0;34m'
+# GRAY='\033[1;30m'
+# NC='\033[0m'
 
-PATHS_LOCALES="packages/checkout-storefront/content/locales apps/saleor-app-checkout/content/locales"
-echo $PATHS_LOCALES
+# PATHS_LOCALES="packages/checkout-storefront/content/locales apps/saleor-app-checkout/content/locales"
+# echo $PATHS_LOCALES
 
-# pnpm run lint
-pnpm run i18n:extract
-pnpm exec prettier --write $PATHS_LOCALES
+# # pnpm run lint
+# pnpm run i18n:extract
+# pnpm exec prettier --write $PATHS_LOCALES
 
-if git diff --quiet $PATHS_LOCALES
-then
-  exit 0
-else 
-  exit 0
-  # echo "${RED}Error: Changes in locales found.${NC}"
-  # echo "${BLUE}Please run ${GRAY}pnpm run i18n:extract${BLUE} and commit the changes.${NC}"
-  # exit 1
-fi
+# if git diff --quiet $PATHS_LOCALES
+# then
+#   exit 0
+# else 
+#   exit 0
+#   # echo "${RED}Error: Changes in locales found.${NC}"
+#   # echo "${BLUE}Please run ${GRAY}pnpm run i18n:extract${BLUE} and commit the changes.${NC}"
+#   # exit 1
+# fi
